# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

update_fastlane

fastlane_version "2.27.0"

default_platform :ios

platform :ios do
  before_all do
    cocoapods    
  end

  desc "Runs all the tests"
  lane :test do
    scan(
      workspace: "BugfenderSDK-iOS-swift-sample.xcworkspace",
      scheme: "BugfenderSDK-iOS-swift-sample")
  end

  
  desc "New build"  
  lane :build do |options|
    clear_derived_data
    increment_build_number(
      build_number: 1
    )
  
    xcodebuild(
      workspace: "BugfenderSDK-iOS-swift-sample.xcworkspace",
      scheme: "BugfenderSDK-iOS-swift-sample",
      configuration: "Debug",
      clean: options[:clean],
      build: true,
      destination: "generic/platform=iOS",
      build_settings: {
        "CODE_SIGNING_REQUIRED" => "NO",
        "CODE_SIGN_IDENTITY" => ""
      }
    )
end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
